name: Lossless Image Compression

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compress images with Calibre Image Actions
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push optimized images
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git diff --cached --quiet || git commit -m "Lossless image compression"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
