name: Create Release Tarball

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get update && sudo apt-get install -y gh

    - name: Create tarballs for each theme directory
      run: |
        for d in */ ; do
          dir=${d%/}
          tar -czf "$dir.tar.gz" "$dir"
        done

    - name: Upload tarballs as artifacts (for master branch pushes)
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: theme-tarballs
        path: "*.tar.gz"

    - name: Create or update GitHub Release for master
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release view master-release || gh release create master-release --title "master-release" --notes "Latest master branch tarballs"
        gh release upload master-release *.tar.gz --clobber

    - name: Create or update GitHub Release for tags
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        gh release view "$tag" || gh release create "$tag" --title "$tag" --generate-notes
        gh release upload "$tag" *.tar.gz --clobber
